### ISSUE TITLE
Evoluir RichPicture "Geral"

### ISSUE THREAD

**Issue by MarcosNBJ** [MarcosNBJ/2019.1-RocketChat#2]
Deverá ser criada uma segunda versão do RichPicture "Geral", com fluxo e mais dinamismo, menos aparência de mapa mental.

**Comment by zarbielli** [comment]
Commits:
81302970ce702ed3efd090d33ca63e60235ea597
4a4db279cda69476156e76d82b08d8a8e57c0f1c
