### ISSUE TITLE
Elicitação - Entrevista

### ISSUE THREAD

**Issue by GabrielDVpereira** [MarcosNBJ/2019.1-RocketChat#7]
Criação e realização da entrevista ao desenvolvedor do app. Lembrar de criar perguntas visando colocar o entrevistado como um usuário do app, por isso buscaremos explorar seu ponto de vista com relação a diferenciais, pontos positivos e negativos sobre a plataforma

**Comment by zarbielli** [comment]
Donne, commit:
c85f269234333af642cb41e19baea51919d5d72d
f792b37870cba6a0502873c59ff316705307f98c
